name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
     - dev 
     - master

jobs:
  build-mingw64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: false
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-python-pip

    - uses: actions/checkout@v2

    - name: Debug
      run: python -c "import sysconfig ; print(sysconfig.get_platform())"

    - name: Build and install
      run: pip install .

    - name: Test
      run: python tests/test.py
